-- Ajouter des annonces de test pour pouvoir tester les détails
INSERT INTO listings (
  user_id,
  purpose,
  property_type,
  title,
  description,
  price,
  currency,
  bedrooms,
  bathrooms,
  area,
  address,
  city,
  neighborhood,
  amenities,
  images,
  status
) VALUES 
(
  'f6873620-3d3e-4636-b74d-531721463a03',
  'rent',
  'apartment',
  'Appartement moderne Cocody',
  'Magnifique appartement de 3 chambres avec vue panoramique sur la lagune',
  180000,
  'CFA',
  3,
  2,
  85,
  'Rue des Palmiers, Cocody',
  'Abidjan',
  'Cocody',
  ARRAY['Parking', 'Sécurité 24/7', 'Climatisation', 'Internet'],
  ARRAY['/placeholder.svg'],
  'active'
),
(
  'f6873620-3d3e-4636-b74d-531721463a03',
  'sale',
  'house',
  'Villa individuelle Riviera',
  'Belle villa de 4 chambres avec jardin et piscine privée',
  45000000,
  'CFA',
  4,
  3,
  150,
  'Boulevard de la Riviera',
  'Abidjan',
  'Riviera',
  ARRAY['Piscine', 'Jardin', 'Garage', 'Sécurité'],
  ARRAY['/placeholder.svg'],
  'active'
),
(
  'f6873620-3d3e-4636-b74d-531721463a03',
  'rent',
  'apartment',
  'Studio équipé Plateau',
  'Studio meublé et équipé au cœur du Plateau',
  120000,
  'CFA',
  1,
  1,
  45,
  'Avenue Chardy, Plateau',
  'Abidjan',
  'Plateau',
  ARRAY['Meublé', 'Climatisation', 'Internet', 'Ascenseur'],
  ARRAY['/placeholder.svg'],
  'active'
),
(
  'f6873620-3d3e-4636-b74d-531721463a03',
  'sale',
  'land',
  'Terrain à bâtir Songon',
  'Terrain de 500m² dans un quartier résidentiel calme',
  8000000,
  'CFA',
  NULL,
  NULL,
  500,
  'Quartier résidentiel Songon',
  'Abidjan',
  'Songon',
  ARRAY['Viabilisé', 'Titre foncier'],
  ARRAY['/placeholder.svg'],
  'active'
),
(
  'f6873620-3d3e-4636-b74d-531721463a03',
  'rent',
  'house',
  'Maison familiale Yopougon',
  'Maison de 3 chambres avec cour, idéale pour une famille',
  200000,
  'CFA',
  3,
  2,
  100,
  'Quartier Sideci, Yopougon',
  'Abidjan',
  'Yopougon',
  ARRAY['Cour', 'Parking', 'Sécurité'],
  ARRAY['/placeholder.svg'],
  'active'
);